name: Auto-approve PR
run-name: Checking if PR should be auto-approved

on: pull_request_target

jobs:
  auto-approve:
    name: Perform auto-approve PR
    runs-on: ubuntu-latest
    needs: lint

    permissions:
      pull-requests: write

    steps:
      - name: Auto-approve PR
        uses: hmarr/auto-approve-action@v3
        if: github.actor == "dependabot[bot]" || github.actor == ${{ github.repository_owner }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
