name: Auto-approve PR
run-name: Checking if elegible for auto-approving PR

on: pull_request

jobs:
  auto-approve:
    name: Perform Auto-approve PR
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    if: github.event.pull_request.user.login == ${{ github.repository_owner }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@dece11172ed6b762b5421b294513d628edad7f7d # v2.5.0
        with:
          egress-policy: audit

      - name: Auto-approve PR via seyLu Bot
        uses: hmarr/auto-approve-action@7d0ab8fdbb906da8a6297d373561d5ccb137d98f # v3.2.1
        with:
          github-token: ${{ secrets.SEYLUBOT_PAT }}
