name: Lint
run-name: Linting ${{ github.repository }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: seyLu/reusable-workflows/.github/workflows/py-lint.yaml@d05d0ee217b79e6cc95d57291203e9c8765a7705
